### ISSUE TITLE
feature verification: xcat-inventory osimage

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#131]
what to do:

* [ ] offer a [xcat-inventory osimage test design](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-xcat-inventory-osimage)
* [ ] finished test depending on above design

Related task #127 #128 #129 
Related discussion #50

**Comment by immarvin** [comment]
run the regression test `XCATTEST_DSTMN=10.3.5.8 xcattest -b /home/xcat-inventory.bundle.all`, all passed except 4 failed cases. 
These 4 Failed cases is caused by the updated error message of xcat-inventory, I updated the cases in PR https://github.com/xcat2/xcat-core/pull/5234

you can focus on the new function test on osimage xcat-inventory export/import  @tingtli

**Comment by tingtli** [comment]
https://github.com/xcat2/xcat-core/pull/5240
