### ISSUE TITLE
[Redfish] Framework of perl code for redfish support

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#157]
* [x] mini-design for the framework, from xcat_cmd-->perl--> python
* [x] xcat_cmd perl section implementation.

**Comment by xuweibj** [comment]
Mini design https://github.com/xcat2/xcat-core/wiki/Redfish_support

**Comment by robin2008** [comment]
Two comments:
1, openbmc and redfish are both based on RESTful,  the required access info might be similar, need to consider use same table
2, AGENT.pm should consider to be general to replace the old OPENBMC one.

**Comment by whowutwut** [comment]
@xuweibj and @robin2008 ... I'd like to suggest considering the following before we get too deep in the implementation..  Essentially everything that I mentioned when we did OpenBMC Python support, and we said we want to get there and do that for the "future", well now it's time to look at that.   Since there's no immediate urgency  for Redfish, now is the best time to look at how we can correctly set up this python framework so that it can be reused in either current xCAT, xCAT3, or writing a new Python program that can import this xCAT library..  Similar to how we do `import sys, os, docopt, etc` ... We should have these xCAT modules that anyone can import and tie into their program like an API. 

We know that Perl has scaling issues with httpd, so we should avoid extending the Perl framework for new function.

**Comment by whowutwut** [comment]
@jjohnson42 Yes, let's sync up, I sent you a note.

**Comment by xuweibj** [comment]
@gurevichmark 
For 1, yes we will create new redfish_client.py to deal with data returned.
For 2, currently we have not got any information from boston and openbmc team. Did not know whether they will support ``rflash`` for redfish. So we have no plan for rflash.  If we got information I think we could have a discussion about it.

**Comment by xuweibj** [comment]
@whowutwut 
Until now, I did not get any information from boston team, and openbmc team has no plan about redfish interface. We think the task is not high priority. And  IPMI works well now, we just planned to implement several commands like ``rpower``, ``rsetboot``. What's your idea? And did you got any requirements about redfish support?

**Comment by gurevichmark** [comment]
@xuweibj The code to handle data for xCAT REST API is in `xCAT-server/xCAT-wsapi/xcatws.cgi` Hopefully data returned by redfish node and openbmc node is the same, so no changes would be needed. But I think during UT of redfish work, a few xCAT REST API calls need to be executed.
