### ISSUE TITLE
offer a probe subcommand to parse command.log file

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#303]
The purpose of this request is  to create a utility that can be run against the commands.log and understand at a high level the most used xCAT commands and what is important from the users point of view.  It will also allow  us to focus energy on the correct commands

what to do:

offer a probe subcommand to parse command.log file.
To list
* number of commands run
* min time
* max time
* average time

An example:
```
Processed 1000 records from index xcat-commands-2018.09.11
------------------COMMAND SUMMARY-------------------
|   command   | count |   min  |   max   |   avg   |
  lsdef           122    0.092     1.502     0.181
  rpower           96    0.045    26.827     5.859
  tabdump          92    0.089     0.156     0.102
  xdsh             91    0.034   125.152     3.330
```

The original requirement from https://github.ibm.com/vhu/c910env/issues/359

**Comment by whowutwut** [comment]
@hu-weihua Can we work on this in the internal repo so that we can get the meat of this function implemented very quickly instead of a formal pull request into the xCAT product.  If so then I can leverage the changes that you create during  your  day time  and add more function into it during my day  time...  and perhaps  we  can get something working in the next 24 hours....

**Comment by hu-weihua** [comment]
Outdated task. close this one.
